[2024-07-04T03:26:48.886+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T03:26:48.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:26:43.784993+00:00 [queued]>
[2024-07-04T03:26:48.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:26:43.784993+00:00 [queued]>
[2024-07-04T03:26:48.928+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-04T03:26:48.950+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_task> on 2024-07-04 03:26:43.784993+00:00
[2024-07-04T03:26:48.959+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2024-07-04T03:26:48.964+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'download_data_task', 'manual__2024-07-04T03:26:43.784993+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/store_raw_data_dag.py', '--cfg-path', '/tmp/tmpx16mm4f3']
[2024-07-04T03:26:48.969+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask download_data_task
[2024-07-04T03:26:49.040+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:26:43.784993+00:00 [running]> on host 4b5a441f90b5
[2024-07-04T03:26:49.168+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T03:26:43.784993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T03:26:43.784993+00:00'
[2024-07-04T03:26:49.171+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T03:26:49.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T03:26:49.173+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_raw_data_dag.py", line 33, in download_wildfire_data
    wget.download(fire_points_url, out=path)
  File "/home/airflow/.local/lib/python3.11/site-packages/wget.py", line 506, in download
    (fd, tmpfile) = tempfile.mkstemp(".tmp", prefix=prefix, dir=".")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 358, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 257, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/fire_points.ziphij5y2z1.tmp'
[2024-07-04T03:26:49.187+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_dag, task_id=download_data_task, run_id=manual__2024-07-04T03:26:43.784993+00:00, execution_date=20240704T032643, start_date=20240704T032648, end_date=20240704T032649
[2024-07-04T03:26:49.204+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task download_data_task ([Errno 13] Permission denied: '/opt/airflow/data/fire_points.ziphij5y2z1.tmp'; 62)
[2024-07-04T03:26:49.217+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T03:26:49.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T03:26:49.255+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
