[2024-07-18T00:10:07.801+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T00:10:07.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:09:33.980244+00:00 [queued]>
[2024-07-18T00:10:07.839+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:09:33.980244+00:00 [queued]>
[2024-07-18T00:10:07.840+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-18T00:10:07.858+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_fire_bq_task> on 2024-07-18 00:09:33.980244+00:00
[2024-07-18T00:10:07.868+0000] {standard_task_runner.py:63} INFO - Started process 1641 to run task
[2024-07-18T00:10:07.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fire_data_dag', 'load_fire_bq_task', 'manual__2024-07-18T00:09:33.980244+00:00', '--job-id', '694', '--raw', '--subdir', 'DAGS_FOLDER/fire_data_dag.py', '--cfg-path', '/tmp/tmpq0m5de30']
[2024-07-18T00:10:07.875+0000] {standard_task_runner.py:91} INFO - Job 694: Subtask load_fire_bq_task
[2024-07-18T00:10:07.944+0000] {task_command.py:426} INFO - Running <TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:09:33.980244+00:00 [running]> on host b83e2bee00d2
[2024-07-18T00:10:08.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fire_data_dag' AIRFLOW_CTX_TASK_ID='load_fire_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:09:33.980244+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T00:09:33.980244+00:00'
[2024-07-18T00:10:08.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T00:10:08.068+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-18T00:10:08.069+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bq load  --source_format=NEWLINE_DELIMITED_JSON --json_extension=GEOJSON --autodetect de_zoomcamp_cchow_dataset.wildfire_polygons_2 gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl']
[2024-07-18T00:10:08.090+0000] {subprocess.py:86} INFO - Output:
[2024-07-18T00:10:10.243+0000] {subprocess.py:93} INFO - BigQuery error in load operation: Error processing job 'famous-
[2024-07-18T00:10:10.244+0000] {subprocess.py:93} INFO - muse-426921-s5:bqjob_r6554a824a543f1a5_00000190c32cc59d_1': Access Denied:
[2024-07-18T00:10:10.244+0000] {subprocess.py:93} INFO - BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform
[2024-07-18T00:10:10.244+0000] {subprocess.py:93} INFO - write scope.
[2024-07-18T00:10:10.510+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-18T00:10:10.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T00:10:10.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-18T00:10:10.533+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fire_data_dag, task_id=load_fire_bq_task, run_id=manual__2024-07-18T00:09:33.980244+00:00, execution_date=20240718T000933, start_date=20240718T001007, end_date=20240718T001010
[2024-07-18T00:10:10.555+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 694 for task load_fire_bq_task (Bash command failed. The command returned a non-zero exit code 1.; 1641)
[2024-07-18T00:10:10.578+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-18T00:10:10.603+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T00:10:10.605+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
