[2024-07-09T23:43:30.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T23:43:30.492+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_transformation.start_cluster manual__2024-07-09T23:43:15.460652+00:00 [queued]>
[2024-07-09T23:43:30.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_transformation.start_cluster manual__2024-07-09T23:43:15.460652+00:00 [queued]>
[2024-07-09T23:43:30.506+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-09T23:43:30.529+0000] {taskinstance.py:2330} INFO - Executing <Task(DataprocStartClusterOperator): start_cluster> on 2024-07-09 23:43:15.460652+00:00
[2024-07-09T23:43:30.542+0000] {standard_task_runner.py:63} INFO - Started process 3024 to run task
[2024-07-09T23:43:30.549+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_transformation', 'start_cluster', 'manual__2024-07-09T23:43:15.460652+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpnch0t_0p']
[2024-07-09T23:43:30.556+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask start_cluster
[2024-07-09T23:43:30.646+0000] {task_command.py:426} INFO - Running <TaskInstance: test_transformation.start_cluster manual__2024-07-09T23:43:15.460652+00:00 [running]> on host ea9610d9d6e7
[2024-07-09T23:43:30.799+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_transformation' AIRFLOW_CTX_TASK_ID='start_cluster' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T23:43:15.460652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T23:43:15.460652+00:00'
[2024-07-09T23:43:30.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T23:43:30.804+0000] {dataproc.py:1266} INFO - Starting the cluster: example-cluster
[2024-07-09T23:43:30.804+0000] {baseoperator.py:400} WARNING - DataprocStartClusterOperator.execute cannot be called outside TaskInstance!
[2024-07-09T23:43:30.806+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-09T23:43:30.807+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-07-09T23:43:30.809+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-07-09T23:43:30.979+0000] {dataproc.py:1252} INFO - The cluster "example-cluster" already running!
[2024-07-09T23:43:31.000+0000] {dataproc.py:1275} INFO - Cluster started
[2024-07-09T23:43:31.000+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T23:43:31.016+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_transformation, task_id=start_cluster, run_id=manual__2024-07-09T23:43:15.460652+00:00, execution_date=20240709T234315, start_date=20240709T234330, end_date=20240709T234331
[2024-07-09T23:43:31.084+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-09T23:43:31.130+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-09T23:43:31.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
