[2024-06-27T22:08:29.726+0000] {processor.py:161} INFO - Started process (PID=1263) to work on /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:29.727+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection_dag.py for tasks to queue
[2024-06-27T22:08:29.729+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:08:29.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:29.736+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:08:29.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-06-27T22:08:29.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:29.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection_dag.py took 0.063 seconds
[2024-06-27T22:08:45.586+0000] {processor.py:161} INFO - Started process (PID=1314) to work on /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:45.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection_dag.py for tasks to queue
[2024-06-27T22:08:45.589+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:08:45.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:45.597+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:08:45.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-06-27T22:08:45.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:08:45.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection_dag.py took 0.066 seconds
[2024-06-27T22:09:15.931+0000] {processor.py:161} INFO - Started process (PID=1379) to work on /opt/airflow/dags/connection_dag.py
[2024-06-27T22:09:15.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection_dag.py for tasks to queue
[2024-06-27T22:09:15.935+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:09:15.934+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:09:15.941+0000] {logging_mixin.py:188} INFO - [2024-06-27T22:09:15.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection_dag.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-06-27T22:09:15.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection_dag.py
[2024-06-27T22:09:15.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection_dag.py took 0.062 seconds
