[2024-07-17T23:26:30.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T23:26:30.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:25:56.554599+00:00 [queued]>
[2024-07-17T23:26:30.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:25:56.554599+00:00 [queued]>
[2024-07-17T23:26:30.783+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-17T23:26:30.801+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fire_bq_task> on 2024-07-17 23:25:56.554599+00:00
[2024-07-17T23:26:30.812+0000] {standard_task_runner.py:63} INFO - Started process 899 to run task
[2024-07-17T23:26:30.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fire_data_dag', 'load_fire_bq_task', 'manual__2024-07-17T23:25:56.554599+00:00', '--job-id', '650', '--raw', '--subdir', 'DAGS_FOLDER/fire_data_dag.py', '--cfg-path', '/tmp/tmpo147msxc']
[2024-07-17T23:26:30.819+0000] {standard_task_runner.py:91} INFO - Job 650: Subtask load_fire_bq_task
[2024-07-17T23:26:30.889+0000] {task_command.py:426} INFO - Running <TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:25:56.554599+00:00 [running]> on host b83e2bee00d2
[2024-07-17T23:26:31.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fire_data_dag' AIRFLOW_CTX_TASK_ID='load_fire_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T23:25:56.554599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T23:25:56.554599+00:00'
[2024-07-17T23:26:31.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T23:26:33.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T23:26:33.169+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bq_load.py", line 32, in load_bq
    load_job.result()
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table famous-muse-426921-s5:de_zoomcamp_cchow_dataset.wildfire_polygons_raw. Field geometry.coordinates has changed type from GEOGRAPHY to FLOAT; reason: invalid, message: Provided Schema does not match Table famous-muse-426921-s5:de_zoomcamp_cchow_dataset.wildfire_polygons_raw. Field geometry.coordinates has changed type from GEOGRAPHY to FLOAT
[2024-07-17T23:26:33.183+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fire_data_dag, task_id=load_fire_bq_task, run_id=manual__2024-07-17T23:25:56.554599+00:00, execution_date=20240717T232556, start_date=20240717T232630, end_date=20240717T232633
[2024-07-17T23:26:33.201+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 650 for task load_fire_bq_task (400 Provided Schema does not match Table famous-muse-426921-s5:de_zoomcamp_cchow_dataset.wildfire_polygons_raw. Field geometry.coordinates has changed type from GEOGRAPHY to FLOAT; reason: invalid, message: Provided Schema does not match Table famous-muse-426921-s5:de_zoomcamp_cchow_dataset.wildfire_polygons_raw. Field geometry.coordinates has changed type from GEOGRAPHY to FLOAT; 899)
[2024-07-17T23:26:33.239+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-17T23:26:33.264+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T23:26:33.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
