[2024-07-04T03:09:59.102+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T03:09:59.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:08:53.426542+00:00 [queued]>
[2024-07-04T03:09:59.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:08:53.426542+00:00 [queued]>
[2024-07-04T03:09:59.148+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T03:09:59.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_task> on 2024-07-04 03:08:53.426542+00:00
[2024-07-04T03:09:59.178+0000] {standard_task_runner.py:63} INFO - Started process 438 to run task
[2024-07-04T03:09:59.183+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'download_data_task', 'manual__2024-07-04T03:08:53.426542+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/store_raw_data_dag.py', '--cfg-path', '/tmp/tmpj4ugv2k_']
[2024-07-04T03:09:59.188+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask download_data_task
[2024-07-04T03:09:59.256+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T03:08:53.426542+00:00 [running]> on host a1f4c6255ab3
[2024-07-04T03:09:59.385+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T03:08:53.426542+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T03:08:53.426542+00:00'
[2024-07-04T03:09:59.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T03:09:59.389+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T03:09:59.390+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_raw_data_dag.py", line 28, in download_wildfire_data
    wget.download(fire_points_url,out = path)
  File "/home/airflow/.local/lib/python3.11/site-packages/wget.py", line 506, in download
    (fd, tmpfile) = tempfile.mkstemp(".tmp", prefix=prefix, dir=".")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 358, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 257, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/fire_points.zipi0a7iq_1.tmp'
[2024-07-04T03:09:59.404+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingestion_dag, task_id=download_data_task, run_id=manual__2024-07-04T03:08:53.426542+00:00, execution_date=20240704T030853, start_date=20240704T030959, end_date=20240704T030959
[2024-07-04T03:09:59.421+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task download_data_task ([Errno 13] Permission denied: '/opt/airflow/data/fire_points.zipi0a7iq_1.tmp'; 438)
[2024-07-04T03:09:59.436+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T03:09:59.480+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T03:09:59.485+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
