[2024-07-04T04:39:05.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T04:39:05.132+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.upload_fire_points_task manual__2024-07-04T04:37:55.321691+00:00 [queued]>
[2024-07-04T04:39:05.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.upload_fire_points_task manual__2024-07-04T04:37:55.321691+00:00 [queued]>
[2024-07-04T04:39:05.147+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T04:39:05.172+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_fire_points_task> on 2024-07-04 04:37:55.321691+00:00
[2024-07-04T04:39:05.181+0000] {standard_task_runner.py:63} INFO - Started process 292 to run task
[2024-07-04T04:39:05.187+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'upload_fire_points_task', 'manual__2024-07-04T04:37:55.321691+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/store_raw_data_dag.py', '--cfg-path', '/tmp/tmp47w18o8t']
[2024-07-04T04:39:05.193+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask upload_fire_points_task
[2024-07-04T04:39:05.265+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_dag.upload_fire_points_task manual__2024-07-04T04:37:55.321691+00:00 [running]> on host 291aee0ad412
[2024-07-04T04:39:05.398+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='upload_fire_points_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T04:37:55.321691+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T04:37:55.321691+00:00'
[2024-07-04T04:39:05.401+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T04:39:05.523+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T04:39:05.524+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_raw_data_dag.py", line 53, in upload_to_gcs
    blob.upload_from_filename(source_path)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2959, in upload_from_filename
    self._handle_filename_and_upload(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 2827, in _handle_filename_and_upload
    with open(filename, "rb") as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/fire_points.zip'
[2024-07-04T04:39:05.540+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingestion_dag, task_id=upload_fire_points_task, run_id=manual__2024-07-04T04:37:55.321691+00:00, execution_date=20240704T043755, start_date=20240704T043905, end_date=20240704T043905
[2024-07-04T04:39:05.558+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 49 for task upload_fire_points_task ([Errno 2] No such file or directory: '/opt/airflow/data/fire_points.zip'; 292)
[2024-07-04T04:39:05.600+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T04:39:05.638+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T04:39:05.644+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
