[2024-07-03T20:55:07.880+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:55:07.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:55:07.886+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:55:07.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:55:07.906+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:55:07.891+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:55:07.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:55:07.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.098 seconds
[2024-07-03T20:55:38.294+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:55:38.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:55:38.299+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:55:38.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:55:38.305+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:55:38.303+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:55:38.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:55:38.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.062 seconds
[2024-07-03T20:56:08.411+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:56:08.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:56:08.417+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:56:08.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:56:08.423+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:56:08.421+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:56:08.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:56:08.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.057 seconds
[2024-07-03T20:56:38.957+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:56:38.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:56:38.964+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:56:38.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:56:38.970+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:56:38.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:56:38.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:56:39.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.056 seconds
[2024-07-03T20:57:09.221+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:57:09.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:57:09.229+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:57:09.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:57:09.236+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:57:09.234+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:57:09.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:57:09.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.056 seconds
[2024-07-03T20:57:39.474+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:57:39.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:57:39.479+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:57:39.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:57:39.484+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:57:39.483+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:57:39.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:57:39.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.056 seconds
[2024-07-03T20:58:09.649+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:58:09.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:58:09.656+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:58:09.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:58:09.664+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:58:09.661+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:58:09.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:58:09.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.068 seconds
[2024-07-03T20:58:39.863+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:58:39.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:58:39.869+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:58:39.868+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:58:39.874+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:58:39.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:58:39.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:58:39.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.050 seconds
[2024-07-03T20:59:10.538+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:59:10.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:59:10.544+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:59:10.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:59:10.550+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:59:10.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:59:10.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:59:10.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.053 seconds
[2024-07-03T20:59:41.231+0000] {processor.py:161} INFO - Started process (PID=589) to work on /opt/airflow/dags/connection.py
[2024-07-03T20:59:41.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T20:59:41.269+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:59:41.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T20:59:41.276+0000] {logging_mixin.py:188} INFO - [2024-07-03T20:59:41.274+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T20:59:41.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T20:59:41.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.252 seconds
[2024-07-03T21:00:12.440+0000] {processor.py:161} INFO - Started process (PID=651) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:00:12.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:00:12.446+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:00:12.445+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:00:12.452+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:00:12.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:00:12.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:00:12.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.059 seconds
[2024-07-03T21:00:42.685+0000] {processor.py:161} INFO - Started process (PID=713) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:00:42.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:00:42.687+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:00:42.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:00:42.693+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:00:42.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:00:42.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:00:42.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.052 seconds
[2024-07-03T21:01:13.767+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:01:13.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:01:13.772+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:01:13.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:01:13.778+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:01:13.776+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:01:13.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:01:13.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.058 seconds
[2024-07-03T21:01:43.863+0000] {processor.py:161} INFO - Started process (PID=837) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:01:43.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:01:43.866+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:01:43.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:01:43.871+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:01:43.870+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:01:43.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:01:43.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.049 seconds
[2024-07-03T21:02:14.008+0000] {processor.py:161} INFO - Started process (PID=900) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:02:14.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:02:14.010+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:02:14.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:02:14.016+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:02:14.015+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:02:14.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:02:14.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.050 seconds
[2024-07-03T21:02:44.103+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:02:44.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:02:44.108+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:02:44.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:02:44.114+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:02:44.112+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:02:44.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:02:44.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.063 seconds
[2024-07-03T21:03:14.441+0000] {processor.py:161} INFO - Started process (PID=1023) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:03:14.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:03:14.444+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:03:14.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:03:14.450+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:03:14.448+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:03:14.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:03:14.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.060 seconds
[2024-07-03T21:03:45.462+0000] {processor.py:161} INFO - Started process (PID=1084) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:03:45.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:03:45.465+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:03:45.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:03:45.471+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:03:45.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:03:45.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:03:45.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.050 seconds
[2024-07-03T21:04:16.269+0000] {processor.py:161} INFO - Started process (PID=1144) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:04:16.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:04:16.274+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:04:16.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:04:16.281+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:04:16.279+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:04:16.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:04:16.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.064 seconds
[2024-07-03T21:04:46.863+0000] {processor.py:161} INFO - Started process (PID=1202) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:04:46.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:04:46.865+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:04:46.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:04:46.870+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:04:46.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:04:46.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:04:46.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.047 seconds
[2024-07-03T21:05:17.705+0000] {processor.py:161} INFO - Started process (PID=1261) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:05:17.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:05:17.709+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:05:17.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:05:17.714+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:05:17.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:05:17.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:05:17.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.049 seconds
[2024-07-03T21:05:47.821+0000] {processor.py:161} INFO - Started process (PID=1320) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:05:47.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:05:47.825+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:05:47.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:05:47.831+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:05:47.829+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:05:47.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:05:47.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.058 seconds
[2024-07-03T21:06:17.914+0000] {processor.py:161} INFO - Started process (PID=1380) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:06:17.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:06:17.917+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:06:17.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:06:17.922+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:06:17.921+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:06:17.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:06:17.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.048 seconds
[2024-07-03T21:06:48.889+0000] {processor.py:161} INFO - Started process (PID=1439) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:06:48.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:06:48.893+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:06:48.892+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:06:48.898+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:06:48.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:06:48.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:06:48.931+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.054 seconds
[2024-07-03T21:07:19.166+0000] {processor.py:161} INFO - Started process (PID=1497) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:07:19.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:07:19.170+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:07:19.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:07:19.174+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:07:19.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:07:19.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:07:19.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.046 seconds
[2024-07-03T21:07:49.905+0000] {processor.py:161} INFO - Started process (PID=1555) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:07:49.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:07:49.909+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:07:49.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:07:49.914+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:07:49.912+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:07:49.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:07:49.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.047 seconds
[2024-07-03T21:08:20.130+0000] {processor.py:161} INFO - Started process (PID=1615) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:08:20.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:08:20.134+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:08:20.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:08:20.140+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:08:20.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:08:20.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:08:20.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.056 seconds
[2024-07-03T21:08:50.213+0000] {processor.py:161} INFO - Started process (PID=1674) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:08:50.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:08:50.216+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:08:50.215+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:08:50.221+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:08:50.219+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:08:50.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:08:50.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.047 seconds
[2024-07-03T21:09:20.657+0000] {processor.py:161} INFO - Started process (PID=1733) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:09:20.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:09:20.660+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:09:20.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:09:20.665+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:09:20.664+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:09:20.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:09:20.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.054 seconds
[2024-07-03T21:09:50.849+0000] {processor.py:161} INFO - Started process (PID=1791) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:09:50.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:09:50.851+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:09:50.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:09:50.856+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:09:50.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:09:50.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:09:50.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.045 seconds
[2024-07-03T21:10:21.184+0000] {processor.py:161} INFO - Started process (PID=1849) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:10:21.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:10:21.187+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:10:21.187+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:10:21.192+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:10:21.191+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:10:21.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:10:21.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.049 seconds
[2024-07-03T21:10:51.885+0000] {processor.py:161} INFO - Started process (PID=1908) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:10:51.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:10:51.889+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:10:51.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:10:51.894+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:10:51.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:10:51.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:10:51.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.049 seconds
[2024-07-03T21:11:22.603+0000] {processor.py:161} INFO - Started process (PID=1968) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:11:22.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:11:22.606+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:11:22.606+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:11:22.611+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:11:22.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:11:22.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:11:22.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.045 seconds
[2024-07-03T21:11:53.569+0000] {processor.py:161} INFO - Started process (PID=2027) to work on /opt/airflow/dags/connection.py
[2024-07-03T21:11:53.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/connection.py for tasks to queue
[2024-07-03T21:11:53.572+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:11:53.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/connection.py
[2024-07-03T21:11:53.577+0000] {logging_mixin.py:188} INFO - [2024-07-03T21:11:53.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/connection.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/connection.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/__init__.py)
[2024-07-03T21:11:53.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/connection.py
[2024-07-03T21:11:53.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/connection.py took 0.047 seconds
