[2024-07-04T04:06:49.086+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T04:06:49.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T04:05:41.161411+00:00 [queued]>
[2024-07-04T04:06:49.130+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T04:05:41.161411+00:00 [queued]>
[2024-07-04T04:06:49.131+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T04:06:49.153+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_task> on 2024-07-04 04:05:41.161411+00:00
[2024-07-04T04:06:49.162+0000] {standard_task_runner.py:63} INFO - Started process 140 to run task
[2024-07-04T04:06:49.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'download_data_task', 'manual__2024-07-04T04:05:41.161411+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/store_raw_data_dag.py', '--cfg-path', '/tmp/tmpzdf3wld9']
[2024-07-04T04:06:49.173+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask download_data_task
[2024-07-04T04:06:49.243+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_dag.download_data_task manual__2024-07-04T04:05:41.161411+00:00 [running]> on host 4a8f13db195c
[2024-07-04T04:06:49.383+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T04:05:41.161411+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T04:05:41.161411+00:00'
[2024-07-04T04:06:49.386+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T04:06:49.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T04:06:49.389+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/store_raw_data_dag.py", line 32, in download_wildfire_data
    wget.download(fire_points_url, out=path)
  File "/home/airflow/.local/lib/python3.11/site-packages/wget.py", line 506, in download
    (fd, tmpfile) = tempfile.mkstemp(".tmp", prefix=prefix, dir=".")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 358, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/tempfile.py", line 257, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/fire_points.zipn_l93rih.tmp'
[2024-07-04T04:06:49.404+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingestion_dag, task_id=download_data_task, run_id=manual__2024-07-04T04:05:41.161411+00:00, execution_date=20240704T040541, start_date=20240704T040649, end_date=20240704T040649
[2024-07-04T04:06:49.421+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task download_data_task ([Errno 13] Permission denied: '/opt/airflow/data/fire_points.zipn_l93rih.tmp'; 140)
[2024-07-04T04:06:49.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T04:06:49.497+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T04:06:49.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
