[2024-07-18T00:00:03.868+0000] {processor.py:161} INFO - Started process (PID=10111) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:03.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:00:03.871+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:00:03.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:03.960+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:00:03.958+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:00:03.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:03.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.140 seconds
[2024-07-18T00:00:34.233+0000] {processor.py:161} INFO - Started process (PID=10172) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:34.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:00:34.236+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:00:34.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:34.330+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:00:34.327+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:00:34.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:00:34.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.146 seconds
[2024-07-18T00:01:05.068+0000] {processor.py:161} INFO - Started process (PID=10233) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:05.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:01:05.071+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:01:05.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:05.140+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:01:05.138+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:01:05.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:05.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.115 seconds
[2024-07-18T00:01:35.739+0000] {processor.py:161} INFO - Started process (PID=10295) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:35.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:01:35.742+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:01:35.741+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:35.812+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:01:35.810+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:01:35.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:01:35.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.113 seconds
[2024-07-18T00:02:06.385+0000] {processor.py:161} INFO - Started process (PID=10357) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:06.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:02:06.389+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:02:06.389+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:06.479+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:02:06.476+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:02:06.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:06.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.146 seconds
[2024-07-18T00:02:36.773+0000] {processor.py:161} INFO - Started process (PID=10418) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:36.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:02:36.776+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:02:36.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:36.852+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:02:36.849+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:02:36.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:02:36.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.125 seconds
[2024-07-18T00:03:07.027+0000] {processor.py:161} INFO - Started process (PID=10480) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:07.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:03:07.030+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:03:07.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:07.114+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:03:07.112+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:03:07.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:07.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.127 seconds
[2024-07-18T00:03:38.067+0000] {processor.py:161} INFO - Started process (PID=10540) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:38.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:03:38.070+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:03:38.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:38.144+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:03:38.142+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:03:38.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:03:38.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.117 seconds
[2024-07-18T00:04:08.435+0000] {processor.py:161} INFO - Started process (PID=10601) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:08.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:04:08.439+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:04:08.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:08.524+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:04:08.521+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:04:08.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:08.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.130 seconds
[2024-07-18T00:04:38.767+0000] {processor.py:161} INFO - Started process (PID=10662) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:38.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:04:38.770+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:04:38.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:38.868+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:04:38.862+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:04:38.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:04:38.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.150 seconds
[2024-07-18T00:05:09.012+0000] {processor.py:161} INFO - Started process (PID=10723) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:09.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:05:09.016+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:05:09.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:09.088+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:05:09.086+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:05:09.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:09.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.120 seconds
[2024-07-18T00:05:39.988+0000] {processor.py:161} INFO - Started process (PID=10783) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:39.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:05:39.991+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:05:39.990+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:40.076+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:05:40.074+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:05:40.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:05:40.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.126 seconds
[2024-07-18T00:06:10.489+0000] {processor.py:161} INFO - Started process (PID=10844) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:10.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:06:10.493+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:06:10.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:10.573+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:06:10.571+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:06:10.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:10.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.123 seconds
[2024-07-18T00:06:41.243+0000] {processor.py:161} INFO - Started process (PID=10905) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:41.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:06:41.247+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:06:41.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:41.334+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:06:41.331+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:06:41.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:06:41.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.132 seconds
[2024-07-18T00:07:12.050+0000] {processor.py:161} INFO - Started process (PID=10966) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:12.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:07:12.053+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:07:12.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:12.142+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:07:12.139+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:07:12.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:12.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.137 seconds
[2024-07-18T00:07:42.747+0000] {processor.py:161} INFO - Started process (PID=11027) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:42.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:07:42.750+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:07:42.749+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:42.823+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:07:42.821+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:07:42.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:07:42.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.114 seconds
[2024-07-18T00:08:13.516+0000] {processor.py:161} INFO - Started process (PID=11089) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:13.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:08:13.521+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:08:13.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:13.613+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:08:13.610+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:08:13.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:13.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.141 seconds
[2024-07-18T00:08:44.550+0000] {processor.py:161} INFO - Started process (PID=11150) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:44.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:08:44.552+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:08:44.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:44.626+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:08:44.624+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:08:44.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:08:44.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.118 seconds
[2024-07-18T00:09:15.357+0000] {processor.py:161} INFO - Started process (PID=11211) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:15.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:09:15.361+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:09:15.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:15.438+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:09:15.436+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:09:15.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:15.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.123 seconds
[2024-07-18T00:09:45.785+0000] {processor.py:161} INFO - Started process (PID=11272) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:45.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:09:45.793+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:09:45.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:45.908+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:09:45.905+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:09:45.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:09:45.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.179 seconds
[2024-07-18T00:10:16.133+0000] {processor.py:161} INFO - Started process (PID=11333) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:16.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:10:16.136+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:10:16.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:16.224+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:10:16.221+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:10:16.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:16.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.133 seconds
[2024-07-18T00:10:46.725+0000] {processor.py:161} INFO - Started process (PID=11394) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:46.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:10:46.730+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:10:46.729+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:46.815+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:10:46.813+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:10:46.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:10:46.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.133 seconds
[2024-07-18T00:11:17.653+0000] {processor.py:161} INFO - Started process (PID=11455) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:17.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:11:17.655+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:11:17.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:17.731+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:11:17.729+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:11:17.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:17.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.118 seconds
[2024-07-18T00:11:48.629+0000] {processor.py:161} INFO - Started process (PID=11517) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:48.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:11:48.633+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:11:48.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:48.709+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:11:48.706+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:11:48.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:11:48.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.118 seconds
[2024-07-18T00:12:18.783+0000] {processor.py:161} INFO - Started process (PID=11577) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:18.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:12:18.785+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:12:18.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:18.853+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:12:18.851+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:12:18.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:18.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.110 seconds
[2024-07-18T00:12:49.351+0000] {processor.py:161} INFO - Started process (PID=11638) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:49.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:12:49.355+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:12:49.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:49.423+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:12:49.421+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:12:49.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:12:49.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.112 seconds
[2024-07-18T00:13:19.629+0000] {processor.py:161} INFO - Started process (PID=11699) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:19.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:13:19.632+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:13:19.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:19.700+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:13:19.698+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:13:19.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:19.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.111 seconds
[2024-07-18T00:13:50.119+0000] {processor.py:161} INFO - Started process (PID=11760) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:50.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:13:50.123+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:13:50.122+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:50.197+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:13:50.195+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:13:50.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:13:50.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.123 seconds
[2024-07-18T00:14:21.270+0000] {processor.py:161} INFO - Started process (PID=11821) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:21.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:14:21.273+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:14:21.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:21.352+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:14:21.350+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:14:21.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:21.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.126 seconds
[2024-07-18T00:14:51.603+0000] {processor.py:161} INFO - Started process (PID=11883) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:51.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:14:51.608+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:14:51.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:51.698+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:14:51.695+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:14:51.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:14:51.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.140 seconds
[2024-07-18T00:15:22.846+0000] {processor.py:161} INFO - Started process (PID=11944) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:22.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:15:22.849+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:15:22.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:22.934+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:15:22.932+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:15:22.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:22.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.131 seconds
[2024-07-18T00:15:53.168+0000] {processor.py:161} INFO - Started process (PID=12005) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:53.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:15:53.172+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:15:53.171+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:53.242+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:15:53.239+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:15:53.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:15:53.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.116 seconds
[2024-07-18T00:16:23.335+0000] {processor.py:161} INFO - Started process (PID=12065) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:23.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:16:23.338+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:16:23.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:23.410+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:16:23.408+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:16:23.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:23.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.116 seconds
[2024-07-18T00:16:53.560+0000] {processor.py:161} INFO - Started process (PID=12126) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:53.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:16:53.563+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:16:53.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:53.632+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:16:53.630+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:16:53.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:16:53.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.111 seconds
[2024-07-18T00:17:23.780+0000] {processor.py:161} INFO - Started process (PID=12187) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:23.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:17:23.783+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:17:23.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:23.851+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:17:23.849+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:17:23.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:23.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.110 seconds
[2024-07-18T00:17:53.985+0000] {processor.py:161} INFO - Started process (PID=12248) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:53.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:17:53.989+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:17:53.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:54.057+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:17:54.055+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:17:54.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:17:54.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.110 seconds
[2024-07-18T00:18:24.238+0000] {processor.py:161} INFO - Started process (PID=12308) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:18:24.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:18:24.242+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:18:24.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:18:24.319+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:18:24.317+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:18:24.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:18:24.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.119 seconds
[2024-07-18T00:28:28.827+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:28.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:28:28.833+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:28:28.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:28.933+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:28:28.929+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:28:28.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:28.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.149 seconds
[2024-07-18T00:28:59.484+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:59.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:28:59.489+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:28:59.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:59.575+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:28:59.572+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:28:59.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:28:59.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.135 seconds
[2024-07-18T00:29:30.049+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:29:30.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:29:30.061+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:29:30.060+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:29:30.116+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:29:30.114+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:29:30.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:29:30.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.103 seconds
[2024-07-18T00:30:00.582+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:00.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:30:00.587+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:30:00.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:00.641+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:30:00.640+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:30:00.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:00.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.095 seconds
[2024-07-18T00:30:31.217+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:31.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:30:31.221+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:30:31.221+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:31.277+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:30:31.275+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:30:31.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:30:31.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.096 seconds
[2024-07-18T00:31:01.670+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:01.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:31:01.674+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:31:01.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:01.728+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:31:01.726+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:31:01.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:01.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.093 seconds
[2024-07-18T00:31:32.137+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:32.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:31:32.142+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:31:32.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:32.197+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:31:32.195+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:31:32.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:31:32.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.096 seconds
[2024-07-18T00:32:02.840+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:32:02.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:32:02.845+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:32:02.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:32:02.900+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:32:02.898+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:32:02.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:32:02.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.096 seconds
[2024-07-18T00:38:09.129+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:09.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:38:09.150+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:38:09.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:09.337+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:38:09.331+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:38:09.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:09.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.321 seconds
[2024-07-18T00:38:40.135+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:40.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:38:40.141+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:38:40.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:40.240+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:38:40.237+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:38:40.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:38:40.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.152 seconds
[2024-07-18T00:39:10.562+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:10.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:39:10.567+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:39:10.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:10.636+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:39:10.633+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:39:10.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:10.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.119 seconds
[2024-07-18T00:39:41.284+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:41.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:39:41.290+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:39:41.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:41.360+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:39:41.357+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:39:41.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:39:41.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.116 seconds
[2024-07-18T00:40:11.461+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:11.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:40:11.465+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:40:11.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:11.530+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:40:11.528+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:40:11.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:11.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.107 seconds
[2024-07-18T00:40:41.859+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:41.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:40:41.865+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:40:41.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:42.062+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:40:42.059+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:40:42.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:40:42.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.308 seconds
[2024-07-18T00:41:12.700+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:12.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:41:12.704+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:41:12.704+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:12.767+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:41:12.764+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:41:12.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:12.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.107 seconds
[2024-07-18T00:41:43.363+0000] {processor.py:161} INFO - Started process (PID=521) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:43.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:41:43.369+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:41:43.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:43.441+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:41:43.438+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:41:43.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:41:43.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.124 seconds
[2024-07-18T00:42:13.661+0000] {processor.py:161} INFO - Started process (PID=582) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:13.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:42:13.666+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:42:13.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:13.739+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:42:13.736+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:42:13.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:13.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.121 seconds
[2024-07-18T00:42:43.818+0000] {processor.py:161} INFO - Started process (PID=643) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:43.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:42:43.824+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:42:43.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:43.891+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:42:43.889+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:42:43.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:42:43.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.115 seconds
[2024-07-18T00:43:14.647+0000] {processor.py:161} INFO - Started process (PID=704) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:14.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:43:14.651+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:43:14.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:14.718+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:43:14.716+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:43:14.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:14.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.111 seconds
[2024-07-18T00:43:45.232+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:45.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:43:45.239+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:43:45.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:45.320+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:43:45.318+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:43:45.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:43:45.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.135 seconds
[2024-07-18T00:44:15.660+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:15.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:44:15.666+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:44:15.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:15.736+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:44:15.734+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:44:15.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:15.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.121 seconds
[2024-07-18T00:44:45.961+0000] {processor.py:161} INFO - Started process (PID=887) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:45.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:44:45.969+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:44:45.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:46.050+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:44:46.047+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:44:46.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:44:46.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.139 seconds
[2024-07-18T00:45:16.461+0000] {processor.py:161} INFO - Started process (PID=950) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:16.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:45:16.468+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:45:16.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:16.546+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:45:16.543+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:45:16.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:16.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.133 seconds
[2024-07-18T00:45:47.257+0000] {processor.py:161} INFO - Started process (PID=1013) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:47.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:45:47.264+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:45:47.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:47.336+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:45:47.334+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:45:47.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:45:47.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.126 seconds
[2024-07-18T00:46:17.678+0000] {processor.py:161} INFO - Started process (PID=1073) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:17.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:46:17.683+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:46:17.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:17.756+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:46:17.754+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:46:17.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:17.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.120 seconds
[2024-07-18T00:46:48.169+0000] {processor.py:161} INFO - Started process (PID=1134) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:48.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:46:48.175+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:46:48.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:48.249+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:46:48.246+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:46:48.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:46:48.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.122 seconds
[2024-07-18T00:47:18.633+0000] {processor.py:161} INFO - Started process (PID=1195) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:18.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:47:18.638+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:47:18.637+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:18.702+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:47:18.700+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:47:18.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:18.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.111 seconds
[2024-07-18T00:47:49.102+0000] {processor.py:161} INFO - Started process (PID=1255) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:49.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T00:47:49.106+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:47:49.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:49.176+0000] {logging_mixin.py:188} INFO - [2024-07-18T00:47:49.174+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T00:47:49.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T00:47:49.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.114 seconds
[2024-07-18T20:37:56.368+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:37:56.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:37:56.375+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:37:56.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:37:56.809+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:37:56.805+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:37:56.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:37:56.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.492 seconds
[2024-07-18T20:38:26.953+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:26.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:38:26.957+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:38:26.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:27.050+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:38:27.047+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:38:27.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:27.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.140 seconds
[2024-07-18T20:38:57.358+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:57.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:38:57.362+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:38:57.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:57.428+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:38:57.426+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:38:57.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:38:57.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.113 seconds
[2024-07-18T20:39:28.165+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:28.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:39:28.168+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:39:28.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:28.235+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:39:28.233+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:39:28.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:28.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.113 seconds
[2024-07-18T20:39:58.903+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:58.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:39:58.917+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:39:58.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:59.111+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:39:59.108+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:39:59.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:39:59.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.305 seconds
[2024-07-18T20:40:29.390+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:40:29.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:40:29.393+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:40:29.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:40:29.462+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:40:29.460+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:40:29.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:40:29.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.111 seconds
[2024-07-18T20:41:00.034+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:00.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:41:00.037+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:41:00.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:00.108+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:41:00.106+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:41:00.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:00.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.113 seconds
[2024-07-18T20:41:30.570+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:30.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:41:30.572+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:41:30.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:30.659+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:41:30.656+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:41:30.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:41:30.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.132 seconds
[2024-07-18T20:42:01.280+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:42:01.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/store_raw_data_dag.py for tasks to queue
[2024-07-18T20:42:01.284+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:42:01.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:42:01.351+0000] {logging_mixin.py:188} INFO - [2024-07-18T20:42:01.349+0000] {dagbag.py:452} ERROR - Failed to bag_dag: /opt/airflow/dags/store_raw_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 448, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 467, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 475, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
    ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 80, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dag_cycle_tester.py", line 66, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: ingestion_dag. Faulty task: load_rec_bq_task
[2024-07-18T20:42:01.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/store_raw_data_dag.py
[2024-07-18T20:42:01.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/store_raw_data_dag.py took 0.113 seconds
