[2024-07-17T23:48:50.362+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T23:48:50.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:47:38.832116+00:00 [queued]>
[2024-07-17T23:48:50.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:47:38.832116+00:00 [queued]>
[2024-07-17T23:48:50.419+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-17T23:48:50.449+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fire_bq_task> on 2024-07-17 23:47:38.832116+00:00
[2024-07-17T23:48:50.460+0000] {standard_task_runner.py:63} INFO - Started process 1295 to run task
[2024-07-17T23:48:50.467+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fire_data_dag', 'load_fire_bq_task', 'manual__2024-07-17T23:47:38.832116+00:00', '--job-id', '678', '--raw', '--subdir', 'DAGS_FOLDER/fire_data_dag.py', '--cfg-path', '/tmp/tmpnglgmva_']
[2024-07-17T23:48:50.469+0000] {standard_task_runner.py:91} INFO - Job 678: Subtask load_fire_bq_task
[2024-07-17T23:48:50.560+0000] {task_command.py:426} INFO - Running <TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T23:47:38.832116+00:00 [running]> on host b83e2bee00d2
[2024-07-17T23:48:50.709+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fire_data_dag' AIRFLOW_CTX_TASK_ID='load_fire_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T23:47:38.832116+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T23:47:38.832116+00:00'
[2024-07-17T23:48:50.713+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T23:48:52.429+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T23:48:52.429+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bq_load.py", line 38, in load_bq
    load_job.result()
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl; reason: invalid, location: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl, message: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl; reason: invalid, message: Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl, message: Error while reading data, error message: JSON parsing error in row starting at position 0: Array specified for non-repeated field: geometry.coordinates. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl
[2024-07-17T23:48:52.444+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fire_data_dag, task_id=load_fire_bq_task, run_id=manual__2024-07-17T23:47:38.832116+00:00, execution_date=20240717T234738, start_date=20240717T234850, end_date=20240717T234852
[2024-07-17T23:48:52.463+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 678 for task load_fire_bq_task (400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl; reason: invalid, location: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl, message: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl; reason: invalid, message: Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl, message: Error while reading data, error message: JSON parsing error in row starting at position 0: Array specified for non-repeated field: geometry.coordinates. File: gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl; 1295)
[2024-07-17T23:48:52.516+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-17T23:48:52.548+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T23:48:52.555+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
