[2024-07-09T20:57:32.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T20:57:32.092+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-09T20:57:18.830592+00:00 [queued]>
[2024-07-09T20:57:32.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-09T20:57:18.830592+00:00 [queued]>
[2024-07-09T20:57:32.113+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-09T20:57:32.142+0000] {taskinstance.py:2330} INFO - Executing <Task(DataprocSubmitJobOperator): pyspark_task> on 2024-07-09 20:57:18.830592+00:00
[2024-07-09T20:57:32.155+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2024-07-09T20:57:32.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_transformation', 'pyspark_task', 'manual__2024-07-09T20:57:18.830592+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmp0xm8v3sd']
[2024-07-09T20:57:32.168+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask pyspark_task
[2024-07-09T20:57:32.273+0000] {task_command.py:426} INFO - Running <TaskInstance: test_transformation.pyspark_task manual__2024-07-09T20:57:18.830592+00:00 [running]> on host ea9610d9d6e7
[2024-07-09T20:57:32.453+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_transformation' AIRFLOW_CTX_TASK_ID='pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T20:57:18.830592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T20:57:18.830592+00:00'
[2024-07-09T20:57:32.457+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T20:57:32.458+0000] {dataproc.py:2553} INFO - Submitting job
[2024-07-09T20:57:32.460+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-09T20:57:32.461+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-07-09T20:57:32.463+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-07-09T20:57:32.674+0000] {dataproc.py:2565} INFO - Job f965d83a-2d2c-4603-8d22-43ec75e2b98d submitted successfully.
[2024-07-09T20:57:32.700+0000] {dataproc.py:2600} INFO - Waiting for job f965d83a-2d2c-4603-8d22-43ec75e2b98d to complete
[2024-07-09T20:58:12.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T20:58:12.993+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2601, in execute
    self.hook.wait_for_job(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 829, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "famous-muse-426921-s5"
  job_id: "f965d83a-2d2c-4603-8d22-43ec75e2b98d"
}
placement {
  cluster_name: "example-cluster"
  cluster_uuid: "6b4e5ccb-344c-439c-a7c1-a2ed1c720730"
}
pyspark_job {
  main_python_file_uri: "gs://de-zoomcamp-cchow-bucket/transformation.py"
  args: "--project_id=famous-muse-426921-s5"
  args: "--bucket=de-zoomcamp-cchow-bucket"
  jar_file_uris: "gs://de-zoomcamp-cchow-bucket/spark-bigquery-with-dependencies_2.12-0.29.0.jar"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d?project=famous-muse-426921-s5&region=us-west1\ngcloud dataproc jobs wait \'f965d83a-2d2c-4603-8d22-43ec75e2b98d\' --region \'us-west1\' --project \'famous-muse-426921-s5\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/\ngs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/driveroutput.*"
  state_start_time {
    seconds: 1720558688
    nanos: 788087000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1720558652
    nanos: 654759000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1720558652
    nanos: 690307000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1720558653
    nanos: 26655000
  }
}
yarn_applications {
  name: "test"
  state: FINISHED
  progress: 1
  tracking_url: "http://example-cluster-m:8088/proxy/application_1720558447601_0001/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/"
job_uuid: "f965d83a-2d2c-4603-8d22-43ec75e2b98d"
done: true

[2024-07-09T20:58:13.001+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test_transformation, task_id=pyspark_task, run_id=manual__2024-07-09T20:57:18.830592+00:00, execution_date=20240709T205718, start_date=20240709T205732, end_date=20240709T205813
[2024-07-09T20:58:13.020+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task pyspark_task (Job failed:
reference {
  project_id: "famous-muse-426921-s5"
  job_id: "f965d83a-2d2c-4603-8d22-43ec75e2b98d"
}
placement {
  cluster_name: "example-cluster"
  cluster_uuid: "6b4e5ccb-344c-439c-a7c1-a2ed1c720730"
}
pyspark_job {
  main_python_file_uri: "gs://de-zoomcamp-cchow-bucket/transformation.py"
  args: "--project_id=famous-muse-426921-s5"
  args: "--bucket=de-zoomcamp-cchow-bucket"
  jar_file_uris: "gs://de-zoomcamp-cchow-bucket/spark-bigquery-with-dependencies_2.12-0.29.0.jar"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d?project=famous-muse-426921-s5&region=us-west1\ngcloud dataproc jobs wait \'f965d83a-2d2c-4603-8d22-43ec75e2b98d\' --region \'us-west1\' --project \'famous-muse-426921-s5\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/\ngs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/driveroutput.*"
  state_start_time {
    seconds: 1720558688
    nanos: 788087000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1720558652
    nanos: 654759000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1720558652
    nanos: 690307000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1720558653
    nanos: 26655000
  }
}
yarn_applications {
  name: "test"
  state: FINISHED
  progress: 1
  tracking_url: "http://example-cluster-m:8088/proxy/application_1720558447601_0001/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/6b4e5ccb-344c-439c-a7c1-a2ed1c720730/jobs/f965d83a-2d2c-4603-8d22-43ec75e2b98d/"
job_uuid: "f965d83a-2d2c-4603-8d22-43ec75e2b98d"
done: true
; 285)
[2024-07-09T20:58:13.043+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T20:58:13.066+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T20:58:13.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
